name: app-dev
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    networks:
      - external

  backend:
    build: ../backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - external

networks:
  external:
    external: true